title: My Wonderful Web Page
author: GitHub User Pat
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my very first site. I do hope you are impressed.
  
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  SBS-PHOYT # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
